[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-cache>=1.0",
    "pytest-subtests>=0.14.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
